"""
Seed : python manage.py shell < api/seed.py
"""
from api.models import Level, Module, Exercise

print("Nettoyage...")
Level.objects.all().delete()

DATA = [
  {
    "slug":"debutant","title":"Débutant","icon":"🐍","order":1,
    "description":"Les fondations solides de Python. Variables, boucles, fonctions.",
    "color":"#0f2a1e","text_color":"#4ade80","accent":"#22c55e",
    "modules":[
      {"title":"Variables & types","icon":"📦","order":1,"xp_reward":10,"duration_min":10,
       "description":"Stocker et typer des données en Python.",
       "concept":"En Python, une variable est créée par simple affectation. Python est dynamiquement typé : int, float, str, bool, NoneType. Pas besoin de déclarer le type à l'avance.",
       "code":"age = 25\nnom = \"Charles\"\nprix = 19.99\nactif = True\nvide = None\n\nprint(type(age))    # <class 'int'>\nprint(type(nom))    # <class 'str'>\nprint(type(actif))  # <class 'bool'>",
       "exercises":["Crée 5 variables (nom, âge, ville, taille, étudiant) et affiche-les","Utilise type() sur chaque variable et observe le résultat","Calcule ton âge dans 10 ans : 'Dans 10 ans, j\\'aurai X ans'","Teste None avec 'is None' et explique la différence avec == None"]},
      {"title":"Listes & tuples","icon":"📋","order":2,"xp_reward":10,"duration_min":15,
       "description":"Collections ordonnées — mutables et immuables.",
       "concept":"list : mutable, entre crochets []. tuple : immutable, entre parenthèses (). Indexés à partir de 0. Les slices permettent d'extraire des sous-séquences.",
       "code":"fruits = [\"pomme\", \"banane\", \"cerise\"]\nprint(fruits[0])          # pomme\nprint(fruits[-1])         # cerise\nfruits.append(\"mangue\")\nfruits.remove(\"banane\")\n\ncoords = (48.86, 2.35)    # tuple immuable\nprint(len(fruits), coords[0])",
       "exercises":["Crée une liste de 5 villes ivoiriennes, affiche la 3ème","Ajoute 2 villes avec append(), supprime-en une avec remove()","Inverse la liste avec le slicing [::-1]","Crée un tuple GPS et essaie de le modifier — observe l'erreur"]},
      {"title":"Dicts & sets","icon":"🗂️","order":3,"xp_reward":10,"duration_min":15,
       "description":"Paires clé/valeur et collections sans doublons.",
       "concept":"dict : paires clé→valeur entre {}. Accès rapide par clé. set : collection sans doublons, non ordonnée. Opérations ensemblistes : union |, intersection &, différence -.",
       "code":"profil = {\"nom\": \"Charles\", \"age\": 22, \"ville\": \"Abidjan\"}\nprint(profil[\"nom\"])       # Charles\nprofil[\"job\"] = \"Dev\"\nprint(profil.get(\"email\", \"N/A\"))  # N/A\n\nuniques = {1, 2, 2, 3, 3, 3}\nprint(uniques)             # {1, 2, 3}",
       "exercises":["Crée un dict 'profil' avec 4 clés et affiche chaque valeur","Ajoute, modifie et supprime des clés avec del","Crée 2 sets et calcule leur intersection (&) et union (|)","Utilise .get('cle', 'defaut') — explique pourquoi c'est plus sûr"]},
      {"title":"Conditions if/else","icon":"🔀","order":4,"xp_reward":10,"duration_min":10,
       "description":"Prendre des décisions dans le code.",
       "concept":"if / elif / else évaluent des conditions booléennes. Opérateurs de comparaison : ==, !=, <, >, <=, >=. Opérateurs logiques : and, or, not. L'indentation est obligatoire en Python.",
       "code":"note = 14\nif note >= 16:\n    print(\"Très bien\")\nelif note >= 12:\n    print(\"Bien\")\nelif note >= 10:\n    print(\"Passable\")\nelse:\n    print(\"Insuffisant\")\n\n# Ternaire\nstatut = \"majeur\" if note >= 10 else \"mineur\"",
       "exercises":["Classifie un nombre : négatif, zéro, ou positif","FizzBuzz classique jusqu'à 30","Simuler un login : vérifie nom et mdp avec if/else","Calculateur IMC : calcule et affiche la catégorie"]},
      {"title":"Boucles for/while","icon":"🔁","order":5,"xp_reward":10,"duration_min":15,
       "description":"Répéter des actions automatiquement.",
       "concept":"for itère sur une séquence (liste, range, string…). while répète tant qu'une condition est vraie. break arrête la boucle, continue passe à l'itération suivante. enumerate() donne l'index en plus.",
       "code":"for i in range(1, 6):\n    print(f\"{i} * 7 = {i*7}\")\n\nfruits = [\"pomme\", \"poire\", \"mangue\"]\nfor idx, fruit in enumerate(fruits):\n    print(f\"{idx}: {fruit}\")\n\ncompteur = 10\nwhile compteur > 0:\n    compteur -= 3",
       "exercises":["Affiche la table de multiplication de 7 avec for","Calcule la somme de 1 à 100 avec while","Parcours une liste et n'affiche que les éléments pairs","Devine un nombre aléatoire (random.randint) avec while"]},
      {"title":"Fonctions","icon":"⚙️","order":6,"xp_reward":15,"duration_min":20,
       "description":"Réutiliser du code avec des blocs nommés.",
       "concept":"def crée une fonction. return renvoie une valeur (None par défaut). Les paramètres peuvent avoir des valeurs par défaut. *args reçoit plusieurs arguments positionnels, **kwargs des arguments nommés.",
       "code":"def saluer(nom, titre=\"M.\"):\n    return f\"Bonjour {titre} {nom} !\"\n\nprint(saluer(\"Charles\"))          # Bonjour M. Charles !\nprint(saluer(\"Aya\", \"Mme\"))       # Bonjour Mme Aya !\n\ndef somme(*args):\n    return sum(args)\n\nprint(somme(1, 2, 3, 4))          # 10",
       "exercises":["max2(a, b) — retourne le plus grand","fahrenheit_to_celsius(f) avec la formule correcte","somme_variable(*args) qui additionne n'importe combien de nombres","factorielle(n) — fonction récursive"]},
      {"title":"Chaînes de caractères","icon":"✏️","order":7,"xp_reward":10,"duration_min":15,
       "description":"Manipuler et formater du texte.",
       "concept":"Les strings sont immuables. Méthodes essentielles : .upper(), .lower(), .strip(), .split(), .join(), .replace(), .startswith(), .endswith(). f-strings (f\"...\") pour formater élégamment.",
       "code":"texte = \"  Bonjour Abidjan  \"\nprint(texte.strip())           # 'Bonjour Abidjan'\nprint(texte.upper())\nmots = texte.strip().split()   # ['Bonjour', 'Abidjan']\n\nnom, ville = \"Charles\", \"Abidjan\"\nprint(f\"{nom} vit à {ville}.\")\nprint(f\"{'Python':>10}\")        # alignement",
       "exercises":["Compte le nombre de voyelles dans une phrase","Inverse une chaîne sans [::-1] (avec une boucle)","'bonjour le monde' → 'Bonjour Le Monde' sans .title()","palindrome(s) → True si la chaîne est un palindrome"]},
      {"title":"Gestion d'erreurs","icon":"🛡️","order":8,"xp_reward":15,"duration_min":15,
       "description":"Anticiper et gérer les exceptions proprement.",
       "concept":"try/except attrape les erreurs. except TypeErreur pour cibler. else s'exécute si pas d'erreur. finally s'exécute toujours. raise lève une exception. Crée tes propres exceptions avec class MonErreur(Exception).",
       "code":"try:\n    n = int(input(\"Entrez un nombre : \"))\n    resultat = 100 / n\nexcept ValueError:\n    print(\"Ce n'est pas un entier !\")\nexcept ZeroDivisionError:\n    print(\"Division par zéro !\")\nelse:\n    print(f\"100 / {n} = {resultat:.2f}\")\nfinally:\n    print(\"Terminé.\")",
       "exercises":["division(a, b) sécurisée avec try/except","Gère l'ouverture d'un fichier inexistant","class AgeInvalide(Exception) — lève si âge < 0 ou > 150","Boucle qui redemande la saisie tant qu'elle est invalide"]},
      {"title":"Fichiers I/O","icon":"📁","order":9,"xp_reward":15,"duration_min":20,
       "description":"Lire et écrire dans des fichiers texte.",
       "concept":"open() ouvre un fichier. Modes : 'r' lecture, 'w' écriture (écrase), 'a' ajout, 'r+' lecture/écriture. with garantit la fermeture automatique même en cas d'erreur. .read(), .readlines(), .write().",
       "code":"# Écriture\nwith open(\"journal.txt\", \"w\", encoding=\"utf-8\") as f:\n    f.write(\"Première entrée\\n\")\n    f.write(\"Deuxième entrée\\n\")\n\n# Lecture ligne par ligne\nwith open(\"journal.txt\", \"r\", encoding=\"utf-8\") as f:\n    for i, ligne in enumerate(f, 1):\n        print(f\"{i}. {ligne.strip()}\")",
       "exercises":["Sauvegarde 5 prénoms dans un fichier, un par ligne","Relis et affiche chaque ligne numérotée","Mini journal : ajoute une entrée datée avec mode 'a'","Lis un CSV manuellement et affiche chaque ligne sous forme de dict"]},
    ]
  },
  {
    "slug":"intermediaire","title":"Intermédiaire","icon":"🔥","order":2,
    "description":"POO, modules, fonctions avancées, comprehensions.",
    "color":"#1a1f2e","text_color":"#60a5fa","accent":"#3b82f6",
    "modules":[
      {"title":"Modules & packages","icon":"📦","order":1,"xp_reward":15,"duration_min":15,
       "description":"Organiser et réutiliser son code.",
       "concept":"import charge un module. from x import y importe spécifiquement. Un package est un dossier avec __init__.py. La bibliothèque standard Python est immense : os, sys, json, datetime, collections, itertools...",
       "code":"import math\nprint(math.sqrt(16), math.pi)\n\nfrom datetime import datetime, timedelta\ndemain = datetime.now() + timedelta(days=1)\nprint(demain.strftime(\"%d/%m/%Y\"))\n\nimport json\ndata = {\"nom\": \"Charles\", \"age\": 22}\njson_str = json.dumps(data, ensure_ascii=False)\nprint(json_str)",
       "exercises":["Explore os : liste les fichiers du dossier courant","Crée utils.py avec 3 fonctions et importe-les","Sauvegarde et recharge un dict avec json","Explore collections.Counter sur une phrase"]},
      {"title":"POO — classes","icon":"🏗️","order":2,"xp_reward":20,"duration_min":25,
       "description":"Modéliser le monde avec des objets.",
       "concept":"class définit un plan (blueprint). __init__ est le constructeur. self désigne l'instance. Les attributs stockent l'état, les méthodes définissent le comportement. @property crée des attributs calculés.",
       "code":"class Voiture:\n    nb_voitures = 0  # attribut de classe\n\n    def __init__(self, marque, annee):\n        self.marque = marque\n        self.annee = annee\n        Voiture.nb_voitures += 1\n\n    def __str__(self):\n        return f\"{self.marque} ({self.annee})\"\n\n    @property\n    def age(self):\n        return 2024 - self.annee\n\nv = Voiture(\"Toyota\", 2018)\nprint(v, v.age)",
       "exercises":["Etudiant : nom, age, notes[] + méthode moyenne()","Ajoute __str__ et __repr__ à Etudiant","CompteBancaire : depot(), retrait(), solde (protégé)","__eq__ pour comparer deux Etudiant par leur moyenne"]},
      {"title":"Héritage","icon":"🌳","order":3,"xp_reward":20,"duration_min":25,
       "description":"Hiérarchies de classes et polymorphisme.",
       "concept":"Une classe enfant hérite de tous les attributs et méthodes du parent. super() appelle le parent. On peut surcharger (override) les méthodes. isinstance() vérifie le type. Le polymorphisme permet d'appeler la même méthode sur des objets différents.",
       "code":"class Forme:\n    def aire(self):\n        raise NotImplementedError\n\nclass Rectangle(Forme):\n    def __init__(self, l, h):\n        self.l, self.h = l, h\n    def aire(self):\n        return self.l * self.h\n\nclass Cercle(Forme):\n    def __init__(self, r):\n        self.r = r\n    def aire(self):\n        import math\n        return math.pi * self.r ** 2\n\nformes = [Rectangle(3,4), Cercle(5)]\nfor f in formes:\n    print(f\"{f.__class__.__name__}: {f.aire():.2f}\")",
       "exercises":["Vehicule → Voiture / Moto avec super().__init__()","Liste polymorphe : appelle parler() sur différents animaux","Implémente __len__ sur une classe Collection","Utilise abc.ABC et @abstractmethod pour forcer l'implémentation"]},
      {"title":"Lambdas & closures","icon":"λ","order":4,"xp_reward":20,"duration_min":20,
       "description":"Fonctions anonymes et capture de contexte.",
       "concept":"lambda crée une fonction anonyme sur une ligne. Une closure est une fonction interne qui 'capture' des variables de son scope externe — elles persistent même après la fin de la fonction externe.",
       "code":"# Lambda\ndouble = lambda x: x * 2\ntrier = sorted([3,1,4,1,5], key=lambda x: -x)\nprint(double(7), trier)\n\n# Closure\ndef fabrique_multiplicateur(n):\n    def multiplier(x):\n        return x * n      # capture n\n    return multiplier\n\nfois5 = fabrique_multiplicateur(5)\nprint(fois5(9))   # 45",
       "exercises":["Trie une liste de dicts par une clé avec lambda","sorted() par longueur de chaîne décroissante","Closure compteur() : retourne une fonction qui s'incrémente","make_validator(min_val, max_val) → validateur réutilisable"]},
      {"title":"map / filter / zip","icon":"🔧","order":5,"xp_reward":15,"duration_min":15,
       "description":"Programmation fonctionnelle sur les collections.",
       "concept":"map(f, iterable) applique f à chaque élément. filter(f, iterable) garde les éléments où f retourne True. zip(a, b) associe les éléments en paires. Ces fonctions retournent des itérateurs (à convertir avec list()).",
       "code":"nombres = [1, 2, 3, 4, 5, 6]\ncarres = list(map(lambda x: x**2, nombres))\npairs = list(filter(lambda x: x%2==0, nombres))\n\nnoms = [\"Alice\", \"Bob\", \"Charles\"]\nscores = [88, 92, 95]\nfor nom, score in zip(noms, scores):\n    print(f\"{nom}: {score}/100\")",
       "exercises":["Celsius → Fahrenheit sur une liste avec map()","Filtre les mots de plus de 5 lettres","zip() pour créer une liste de dicts {nom, note, ville}","Réécris tout avec des list comprehensions et compare"]},
      {"title":"List comprehensions","icon":"⚡","order":6,"xp_reward":15,"duration_min":15,
       "description":"Transformations concises et pythoniques.",
       "concept":"[expression for item in iterable if condition] — la liste en compréhension est plus lisible et souvent plus rapide qu'une boucle for explicite. Fonctionne aussi pour les dicts {k: v for ...} et les sets {expr for ...}.",
       "code":"# Liste\ncarres = [x**2 for x in range(1, 11)]\npairs = [x for x in range(20) if x % 2 == 0]\n\n# Dict\nlongueurs = {mot: len(mot) for mot in [\"Python\", \"Java\", \"Go\"]}\n\n# Imbriquée\nmatrice = [[i*j for j in range(1,4)] for i in range(1,4)]\nprint(matrice)",
       "exercises":["Nombres premiers jusqu'à 50 avec comprehension","Aplatir [[1,2],[3,4],[5,6]] en [1,2,3,4,5,6]","Dict {mot: longueur} depuis une liste de mots","Tous les couples (i,j) où i ≠ j depuis range(4)"]},
      {"title":"Générateurs","icon":"🌊","order":7,"xp_reward":20,"duration_min":20,
       "description":"Itération paresseuse (lazy) et économie mémoire.",
       "concept":"yield transforme une fonction en générateur — elle produit les valeurs une par une sans tout stocker. Crucial pour les grands ensembles de données. next() tire la prochaine valeur. Les generator expressions (x for x in ...) sont encore plus compactes.",
       "code":"def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\nfib = fibonacci()\nfor _ in range(10):\n    print(next(fib), end=\" \")\n# 0 1 1 2 3 5 8 13 21 34\n\n# Économie mémoire\ncarres_gen = (x**2 for x in range(10_000_000))\nprint(next(carres_gen))  # 0 — rien n'est calculé d'avance",
       "exercises":["fibonacci() infini — prends les 15 premiers avec islice","Générateur de fichier ligne par ligne sans tout charger","Compte_a_rebours(n) — génère n, n-1, ..., 1, 'Partez !'","Compare sys.getsizeof d'une list vs un generator"]},
      {"title":"Décorateurs","icon":"🎀","order":8,"xp_reward":25,"duration_min":25,
       "description":"Modifier le comportement d'une fonction élégamment.",
       "concept":"Un décorateur est une fonction qui prend une fonction et retourne une version améliorée. @decorator est du sucre syntaxique pour func = decorator(func). Utilise functools.wraps pour préserver les métadonnées.",
       "code":"import time\nimport functools\n\ndef chronometre(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        debut = time.perf_counter()\n        resultat = func(*args, **kwargs)\n        duree = time.perf_counter() - debut\n        print(f\"{func.__name__} : {duree:.4f}s\")\n        return resultat\n    return wrapper\n\n@chronometre\ndef somme_lente(n):\n    return sum(range(n))\n\nsomme_lente(1_000_000)",
       "exercises":["@logger : affiche nom, args, valeur retournée","@retry(n=3) : réessaie n fois si exception","@memoize : cache sans functools.lru_cache","Chaîne 2 décorateurs et observe l'ordre d'application"]},
      {"title":"Expressions régulières","icon":"🔍","order":9,"xp_reward":20,"duration_min":20,
       "description":"Chercher et valider des patterns dans du texte.",
       "concept":"Le module re permet de matcher des patterns. Métacaractères : . * + ? [] ^ $ \\d \\w \\s. re.search() trouve la première occurrence. re.findall() trouve toutes les occurrences. re.sub() remplace.",
       "code":"import re\n\ntexte = \"Contactez charles@gmail.com ou aya.kone@yahoo.fr\"\nemails = re.findall(r'[\\w.+-]+@[\\w-]+\\.[a-z]{2,}', texte)\nprint(emails)  # ['charles@gmail.com', 'aya.kone@yahoo.fr']\n\n# Validation\ndef valider_tel(tel):\n    return bool(re.match(r'^\\+?[0-9\\s]{8,15}$', tel))\n\nprint(valider_tel(\"+225 07 06 83 67 22\"))  # True",
       "exercises":["Valide si une chaîne est un email valide","Extrait tous les #hashtags d'un texte","Remplace les numéros de téléphone par '***'","Valide un mdp : 8+ chars, 1 maj, 1 chiffre, 1 spécial"]},
      {"title":"Environnements virtuels","icon":"🔒","order":10,"xp_reward":10,"duration_min":10,
       "description":"Isoler les dépendances par projet.",
       "concept":"venv crée un environnement Python isolé par projet — chaque projet a ses propres packages sans conflit. pip gère les packages. requirements.txt liste les dépendances pour reproduire l'environnement.",
       "code":"# Terminal :\npython -m venv .venv\nsource .venv/bin/activate      # Linux/macOS\n.venv\\Scripts\\activate          # Windows\n\npip install requests fastapi\npip freeze > requirements.txt\n\n# Sur une autre machine :\npip install -r requirements.txt",
       "exercises":["Crée un venv et installe requests","GET sur https://httpbin.org/json et affiche le résultat","Crée requirements.txt et réinstalle dans un nouveau venv","pip show requests : comprends les métadonnées du package"]},
    ]
  },
  {
    "slug":"avance","title":"Avancé","icon":"⚡","order":3,
    "description":"Concurrence, BDD, tests, data science, web APIs.",
    "color":"#1e1a2e","text_color":"#c084fc","accent":"#a855f7",
    "modules":[
      {"title":"Async / await","icon":"🚀","order":1,"xp_reward":30,"duration_min":30,
       "description":"Concurrence légère avec asyncio.",
       "concept":"async def crée une coroutine. await suspend l'exécution et rend la main. asyncio.gather() lance plusieurs coroutines en 'parallèle'. Idéal pour les opérations I/O (réseau, fichiers) car pas de blocage.",
       "code":"import asyncio\n\nasync def fetch_data(url, delay):\n    print(f\"Début fetch {url}\")\n    await asyncio.sleep(delay)  # simule réseau\n    print(f\"Fin fetch {url}\")\n    return f\"data:{url}\"\n\nasync def main():\n    # Lance 3 tâches en parallèle\n    resultats = await asyncio.gather(\n        fetch_data(\"/users\", 1),\n        fetch_data(\"/posts\", 2),\n        fetch_data(\"/comments\", 0.5),\n    )\n    print(resultats)\n\nasyncio.run(main())",
       "exercises":["3 coroutines avec sleep différents, observer l'ordre","aiohttp : fetch 5 URLs en parallèle, mesurer le temps","Producteur/consommateur avec asyncio.Queue","Timeout avec asyncio.wait_for(coroutine, timeout=2.0)"]},
      {"title":"SQLite / SQLAlchemy","icon":"🗄️","order":2,"xp_reward":25,"duration_min":30,
       "description":"Persister des données avec une base SQL.",
       "concept":"sqlite3 est intégré à Python. Connexion → curseur → execute → commit. Les placeholders ? évitent les injections SQL. SQLAlchemy ORM permet de travailler avec des objets Python plutôt que du SQL brut.",
       "code":"import sqlite3\n\nwith sqlite3.connect(\"ecole.db\") as conn:\n    conn.execute(\"\"\"\n        CREATE TABLE IF NOT EXISTS etudiants (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            nom TEXT NOT NULL,\n            note REAL\n        )\n    \"\"\")\n    conn.execute(\n        \"INSERT INTO etudiants (nom, note) VALUES (?, ?)\",\n        (\"Charles\", 15.5)\n    )\n    for row in conn.execute(\"SELECT * FROM etudiants\"):\n        print(row)",
       "exercises":["CRUD complet pour une table contacts","Recherche par nom avec LIKE et % ","100 insertions : mesure le temps avec/sans transaction","Recréer avec SQLAlchemy ORM (Base, Session, query)"]},
      {"title":"Tests unitaires","icon":"✅","order":3,"xp_reward":25,"duration_min":25,
       "description":"Garantir la qualité avec des tests automatisés.",
       "concept":"unittest est inclus dans Python. pytest est plus moderne et populaire. TDD (Test-Driven Development) : écrire les tests AVANT le code. setUp() initialise les fixtures. assertRaises() vérifie les exceptions.",
       "code":"import unittest\n\nclass CompteBancaire:\n    def __init__(self, solde=0):\n        self.solde = solde\n    def deposer(self, montant):\n        if montant <= 0:\n            raise ValueError(\"Montant doit être positif\")\n        self.solde += montant\n\nclass TestCompte(unittest.TestCase):\n    def setUp(self):\n        self.compte = CompteBancaire(100)\n    def test_depot_valide(self):\n        self.compte.deposer(50)\n        self.assertEqual(self.compte.solde, 150)\n    def test_depot_invalide(self):\n        with self.assertRaises(ValueError):\n            self.compte.deposer(-10)\n\nif __name__ == '__main__':\n    unittest.main()",
       "exercises":["Tests complets pour CompteBancaire (retrait, solde négatif)","setUp() + tearDown() pour créer/nettoyer un fichier temporaire","pytest : réécrire les mêmes tests avec assert simple","pytest-cov : mesure la couverture de code"]},
      {"title":"NumPy & Pandas","icon":"📊","order":4,"xp_reward":30,"duration_min":35,
       "description":"Analyser des données tabulaires efficacement.",
       "concept":"NumPy : tableaux N-dimensionnels avec opérations vectorisées (beaucoup plus rapide que les boucles Python). Pandas : DataFrame = table de données avec étiquettes. Inspiré de R. Incontournable en data science.",
       "code":"import numpy as np\nimport pandas as pd\n\n# NumPy\narr = np.array([1,2,3,4,5])\nprint(arr * 2, arr.mean(), arr.std())\n\n# Pandas\ndf = pd.DataFrame({\n    'nom': ['Alice','Bob','Charles','Aya'],\n    'note': [15, 12, 18, 14],\n    'ville': ['Abidjan','Paris','Abidjan','Dakar']\n})\nprint(df[df['note'] >= 14])\nprint(df.groupby('ville')['note'].mean())",
       "exercises":["Charge un CSV avec read_csv() et affiche .describe()","Filtre sur plusieurs conditions avec loc[]","groupby() : moyenne des notes par ville","merge() : joint deux DataFrames comme un SQL JOIN"]},
      {"title":"Flask / FastAPI","icon":"🌐","order":5,"xp_reward":35,"duration_min":40,
       "description":"Créer des APIs REST et applications web.",
       "concept":"Flask : micro-framework minimaliste, grande liberté. FastAPI : moderne, async, validation Pydantic automatique, documentation Swagger auto-générée. Les routes sont décorées avec @app.get(), @app.post()...",
       "code":"from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\nfrom typing import List\n\napp = FastAPI(title=\"API Étudiants\")\netudiants_db = []\n\nclass Etudiant(BaseModel):\n    nom: str\n    note: float\n\n@app.get(\"/etudiants\", response_model=List[Etudiant])\ndef lister():\n    return etudiants_db\n\n@app.post(\"/etudiants\", status_code=201)\ndef ajouter(e: Etudiant):\n    etudiants_db.append(e)\n    return {\"message\": \"Créé\", \"etudiant\": e}",
       "exercises":["API CRUD complète pour gérer des étudiants","Validation Pydantic : note entre 0 et 20","Connecte à SQLite avec SQLAlchemy","Teste via Swagger UI sur /docs"]},
    ]
  },
  {
    "slug":"expert","title":"Expert","icon":"🏆","order":4,
    "description":"Métaclasses, performances, ML, déploiement.",
    "color":"#2a1a0e","text_color":"#fb923c","accent":"#f97316",
    "modules":[
      {"title":"Métaclasses","icon":"🧠","order":1,"xp_reward":50,"duration_min":45,
       "description":"Contrôler la création des classes dynamiquement.",
       "concept":"En Python, tout est objet — même les classes. Une métaclasse est la 'classe d'une classe'. type est la métaclasse par défaut. En définissant __new__ ou __init__ dans une métaclasse, on contrôle comment les classes sont créées.",
       "code":"class Singleton(type):\n    \"\"\"Métaclasse qui garantit une seule instance.\"\"\"\n    _instances = {}\n\n    def __call__(cls, *args, **kwargs):\n        if cls not in cls._instances:\n            cls._instances[cls] = super().__call__(*args, **kwargs)\n        return cls._instances[cls]\n\nclass Config(metaclass=Singleton):\n    def __init__(self):\n        self.debug = False\n\na, b = Config(), Config()\nprint(a is b)          # True — même objet !",
       "exercises":["Métaclasse qui interdit les attributs en MAJUSCULES","Métaclasse Registry : enregistre toutes les sous-classes","Ajoute automatiquement __repr__ à toutes les classes","Étudie comment Django utilise des métaclasses pour les modèles"]},
      {"title":"Optimisation perf","icon":"⚡","order":2,"xp_reward":50,"duration_min":40,
       "description":"Mesurer, profiler et accélérer le code Python.",
       "concept":"'Premature optimization is the root of all evil.' — Profile d'abord avec cProfile, puis optimise. Techniques : __slots__, numpy vectorisation, lru_cache, algorithmes meilleurs, structures de données adaptées.",
       "code":"import cProfile, pstats, io\n\ndef version_lente(n):\n    return [x**2 for x in range(n) if x % 2 == 0]\n\ndef version_rapide(n):\n    import numpy as np\n    arr = np.arange(0, n, 2)\n    return arr ** 2\n\npr = cProfile.Profile()\npr.enable()\nversion_lente(1_000_000)\npr.disable()\nstats = pstats.Stats(pr)\nstats.sort_stats('tottime').print_stats(5)",
       "exercises":["Profile ton code le plus lent et identifie le goulot","__slots__ sur une classe — mesure le gain mémoire","Loop Python → NumPy vectorisé — mesure le speedup","lru_cache sur fibonacci récursif — mesure le gain"]},
      {"title":"ML avec scikit-learn","icon":"🤖","order":3,"xp_reward":60,"duration_min":60,
       "description":"Machine learning pratique avec Python.",
       "concept":"Pipeline ML : données brutes → préprocessing → feature engineering → modèle → évaluation → déploiement. scikit-learn fournit des dizaines d'algorithmes avec une API cohérente : fit(), predict(), score().",
       "code":"from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import Pipeline\nimport numpy as np\n\niris = load_iris()\nX_train, X_test, y_train, y_test = train_test_split(\n    iris.data, iris.target, test_size=0.2, random_state=42\n)\n\npipeline = Pipeline([\n    ('scaler', StandardScaler()),\n    ('clf', RandomForestClassifier(n_estimators=100))\n])\npipeline.fit(X_train, y_train)\nprint(f\"Accuracy: {pipeline.score(X_test, y_test):.2%}\")",
       "exercises":["Entraîne et évalue sur le dataset Iris","Compare KNN, SVM, RandomForest sur le même dataset","GridSearchCV pour optimiser les hyperparamètres","Pipeline complet : StandardScaler + modèle + évaluation"]},
      {"title":"Docker + Python","icon":"🐳","order":4,"xp_reward":60,"duration_min":50,
       "description":"Conteneuriser et déployer ses applications Python.",
       "concept":"Docker empaquète ton app et ses dépendances dans un conteneur portable. Dockerfile définit l'image. docker-compose orchestre plusieurs services. L'image slim réduit la taille. Les variables d'environnement externalisent la config.",
       "code":"# Dockerfile\nFROM python:3.12-slim\n\nWORKDIR /app\n\n# Copier requirements en premier (cache Docker)\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY . .\n\nEXPOSE 8000\n\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n\n# docker-compose.yml :\n# services:\n#   api:\n#     build: .\n#     ports: [\"8000:8000\"]\n#   db:\n#     image: postgres:16",
       "exercises":["Dockerise ton API FastAPI et teste dans le conteneur","Multi-stage build pour réduire la taille de l'image","docker-compose : API + PostgreSQL","Pousse sur Docker Hub et déploie sur un VPS"]},
    ]
  },
]

for lvl_data in DATA:
    mods = lvl_data.pop("modules")
    level = Level.objects.create(**lvl_data)
    print(f"  ✓ Niveau : {level.icon} {level.title}")
    for mod_data in mods:
        exos = mod_data.pop("exercises")
        code = mod_data.pop("code")
        module = Module.objects.create(level=level, code_example=code, **mod_data)
        for i, ex in enumerate(exos, 1):
            Exercise.objects.create(module=module, text=ex, order=i)

print(f"\nSeed terminé ! {Level.objects.count()} niveaux, {Module.objects.count()} modules.")
